7130 TOGGLE Rollback ønskes ikke (#2683)
MELOSYS-7130

vi vil unngå
org.springframework.transaction.UnexpectedRollbackException: Transaction
silently rolled back because it has been marked as rollback-only